data:
  dataset: "example_0"
  splits: [0.7, 0.15, 0.15]
  input_transforms: ["normalize"]
  output_transforms: ["normalize"]
training:
  batch_size: 100
  shuffle: true
  epochs: 1_000
  loss: "l2"
  optimizer: "Adam"
  lr: 1e-2
model:
  variant: "nn_force"
  kwargs:
    system_folder: "example_0"
    layer_list: [32, 32, 2]
    input_dims: 6
    preprocessing: ["flatten_force_args"]
    postprocessing: []
plotting:
  inputs: true
  predictions: true
  difference: true
logging:
  epoch_spacing: 10
  history: true
  model: true
  metrics: []
